name: Continious Delivery

on:
  push:
    branches: [ "main" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Debug
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build Release
      run: dotnet build --no-restore -c release
    - name: Package
      run: dotnet pack -c release
    - name: Publish
      run: dotnet nuget push ./bin/release/EngineBay.SheetFunctions.0.0.2.nupkg --api-key ${{ secrets.NUGET_PUBLISHING_API_KEY }} --source https://api.nuget.org/v3/index.json
