name: Continious Delivery

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test
    - name: Package
      env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: dotnet pack -p:PackageVersion=$RELEASE_VERSION -c release
    - name: Publish
      env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: dotnet nuget push ./bin/Release/EngineBay.SheetFunctions.$RELEASE_VERSION.nupkg --api-key "${{ secrets.NUGET_PUBLISHING_API_KEY }}" --source "https://api.nuget.org/v3/index.json"
